# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Changelog:
#  - 2020-05-15: pkgdown support
#  - 2020-04-23: creation

language: R

r_check_args: --as-cran

sudo: required

cache: packages

warnings_are_errors: false

matrix:
  include:
#    - os: osx
#      r: release
    - os: linux
      r: devel
    - os: linux
      r: release
#      r_packages:
#        - covr
#        - pkgdown
#      after_success:
#        - Rscript -e 'covr::codecov()'
#        - R CMD INSTALL .
#        - Rscript -e 'pkgdown::build_site()'
#      deploy:
#        - provider: pages
#          skip-cleanup: true
#          github-token: $GITHUB_PAT
#          keep-history: true
#          local-dir: docs
#        - provider: releases
#          api_key: $GITHUB_PAT
#          file: $PKG_TARBALL
#          skip_cleanup: true
#          on:
#            tags: true
